# Generated by Django 4.2.2 on 2023-10-17 19:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "author_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name_first", models.CharField(max_length=100)),
                ("name_last", models.CharField(max_length=100)),
                ("birth_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="PublicationCategory",
            fields=[
                (
                    "category_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "publisher_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state_province", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("website", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "journal_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("publication_date", models.DateField()),
                ("volume", models.IntegerField(blank=True, null=True)),
                ("issue", models.IntegerField(blank=True, null=True)),
                ("issn", models.CharField(blank=True, max_length=20, null=True)),
                ("authors", models.ManyToManyField(to="example_bib_app.author")),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, to="example_bib_app.publicationcategory"
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="example_bib_app.publisher",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "book_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("isbn", models.CharField(blank=True, max_length=20, null=True)),
                ("publication_date", models.DateField()),
                ("authors", models.ManyToManyField(to="example_bib_app.author")),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, to="example_bib_app.publicationcategory"
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="example_bib_app.publisher",
                    ),
                ),
            ],
        ),
    ]
