# Generated by Django 4.2.17 on 2024-12-18 16:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("example_bib_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="birth_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="author",
            name="name_first",
            field=models.CharField(help_text="First name of the author", max_length=100),
        ),
        migrations.AlterField(
            model_name="author",
            name="name_last",
            field=models.CharField(help_text="Last name of the author", max_length=100),
        ),
        migrations.AlterField(
            model_name="book",
            name="publication_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="journal",
            name="publication_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="name",
            field=models.CharField(help_text="Name of the publisher", max_length=100),
        ),
    ]
