# Generated by Django 4.2.2 on 2023-10-13 09:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("async_example_bib_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="author_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="book_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="categories",
            field=models.ManyToManyField(
                blank=True, to="async_example_bib_app.publicationcategory"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="journal",
            name="categories",
            field=models.ManyToManyField(
                blank=True, to="async_example_bib_app.publicationcategory"
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="issn",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="journal",
            name="issue",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="journal",
            name="journal_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="volume",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="publicationcategory",
            name="category_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="publisher_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="state_province",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
