// source: socio_bib_example_grpc/v1/example_bib_app.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.dsg_example.example_bib_app.AuthorResponse');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dsg_example.example_bib_app.AuthorResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.dsg_example.example_bib_app.AuthorResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.dsg_example.example_bib_app.AuthorResponse.displayName = 'proto.dsg_example.example_bib_app.AuthorResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dsg_example.example_bib_app.AuthorResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.dsg_example.example_bib_app.AuthorResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dsg_example.example_bib_app.AuthorResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dsg_example.example_bib_app.AuthorResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
authorId: jspb.Message.getFieldWithDefault(msg, 1, ""),
nameFirst: jspb.Message.getFieldWithDefault(msg, 2, ""),
nameLast: jspb.Message.getFieldWithDefault(msg, 3, ""),
birthDate: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dsg_example.example_bib_app.AuthorResponse}
 */
proto.dsg_example.example_bib_app.AuthorResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dsg_example.example_bib_app.AuthorResponse;
  return proto.dsg_example.example_bib_app.AuthorResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dsg_example.example_bib_app.AuthorResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dsg_example.example_bib_app.AuthorResponse}
 */
proto.dsg_example.example_bib_app.AuthorResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAuthorId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setNameFirst(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setNameLast(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setBirthDate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dsg_example.example_bib_app.AuthorResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.dsg_example.example_bib_app.AuthorResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.dsg_example.example_bib_app.AuthorResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dsg_example.example_bib_app.AuthorResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAuthorId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getNameFirst();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getNameLast();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getBirthDate();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional string author_id = 1;
 * @return {string}
 */
proto.dsg_example.example_bib_app.AuthorResponse.prototype.getAuthorId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.dsg_example.example_bib_app.AuthorResponse} returns this
 */
proto.dsg_example.example_bib_app.AuthorResponse.prototype.setAuthorId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string name_first = 2;
 * @return {string}
 */
proto.dsg_example.example_bib_app.AuthorResponse.prototype.getNameFirst = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.dsg_example.example_bib_app.AuthorResponse} returns this
 */
proto.dsg_example.example_bib_app.AuthorResponse.prototype.setNameFirst = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string name_last = 3;
 * @return {string}
 */
proto.dsg_example.example_bib_app.AuthorResponse.prototype.getNameLast = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.dsg_example.example_bib_app.AuthorResponse} returns this
 */
proto.dsg_example.example_bib_app.AuthorResponse.prototype.setNameLast = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string birth_date = 4;
 * @return {string}
 */
proto.dsg_example.example_bib_app.AuthorResponse.prototype.getBirthDate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.dsg_example.example_bib_app.AuthorResponse} returns this
 */
proto.dsg_example.example_bib_app.AuthorResponse.prototype.setBirthDate = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


