// source: socio_bib_example_grpc/v1/example_bib_app.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.dsg_example.example_bib_app.BookPartialUpdateRequest');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dsg_example.example_bib_app.BookPartialUpdateRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.dsg_example.example_bib_app.BookPartialUpdateRequest.repeatedFields_, null);
};
goog.inherits(proto.dsg_example.example_bib_app.BookPartialUpdateRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.dsg_example.example_bib_app.BookPartialUpdateRequest.displayName = 'proto.dsg_example.example_bib_app.BookPartialUpdateRequest';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.dsg_example.example_bib_app.BookPartialUpdateRequest.repeatedFields_ = [3,4,8];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dsg_example.example_bib_app.BookPartialUpdateRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.dsg_example.example_bib_app.BookPartialUpdateRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dsg_example.example_bib_app.BookPartialUpdateRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dsg_example.example_bib_app.BookPartialUpdateRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
bookId: jspb.Message.getFieldWithDefault(msg, 1, ""),
title: jspb.Message.getFieldWithDefault(msg, 2, ""),
authorsList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
categoriesList: (f = jspb.Message.getRepeatedField(msg, 4)) == null ? undefined : f,
isbn: (f = jspb.Message.getField(msg, 5)) == null ? undefined : f,
publisher: jspb.Message.getFieldWithDefault(msg, 6, ""),
publicationDate: jspb.Message.getFieldWithDefault(msg, 7, ""),
partialUpdateFieldsList: (f = jspb.Message.getRepeatedField(msg, 8)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dsg_example.example_bib_app.BookPartialUpdateRequest}
 */
proto.dsg_example.example_bib_app.BookPartialUpdateRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dsg_example.example_bib_app.BookPartialUpdateRequest;
  return proto.dsg_example.example_bib_app.BookPartialUpdateRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dsg_example.example_bib_app.BookPartialUpdateRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dsg_example.example_bib_app.BookPartialUpdateRequest}
 */
proto.dsg_example.example_bib_app.BookPartialUpdateRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setBookId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addAuthors(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.addCategories(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setIsbn(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setPublisher(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setPublicationDate(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.addPartialUpdateFields(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dsg_example.example_bib_app.BookPartialUpdateRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.dsg_example.example_bib_app.BookPartialUpdateRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.dsg_example.example_bib_app.BookPartialUpdateRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dsg_example.example_bib_app.BookPartialUpdateRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBookId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getAuthorsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
  f = message.getCategoriesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      4,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getPublisher();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getPublicationDate();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getPartialUpdateFieldsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      8,
      f
    );
  }
};


/**
 * optional string book_id = 1;
 * @return {string}
 */
proto.dsg_example.example_bib_app.BookPartialUpdateRequest.prototype.getBookId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.dsg_example.example_bib_app.BookPartialUpdateRequest} returns this
 */
proto.dsg_example.example_bib_app.BookPartialUpdateRequest.prototype.setBookId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string title = 2;
 * @return {string}
 */
proto.dsg_example.example_bib_app.BookPartialUpdateRequest.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.dsg_example.example_bib_app.BookPartialUpdateRequest} returns this
 */
proto.dsg_example.example_bib_app.BookPartialUpdateRequest.prototype.setTitle = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated string authors = 3;
 * @return {!Array<string>}
 */
proto.dsg_example.example_bib_app.BookPartialUpdateRequest.prototype.getAuthorsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.dsg_example.example_bib_app.BookPartialUpdateRequest} returns this
 */
proto.dsg_example.example_bib_app.BookPartialUpdateRequest.prototype.setAuthorsList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.dsg_example.example_bib_app.BookPartialUpdateRequest} returns this
 */
proto.dsg_example.example_bib_app.BookPartialUpdateRequest.prototype.addAuthors = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.dsg_example.example_bib_app.BookPartialUpdateRequest} returns this
 */
proto.dsg_example.example_bib_app.BookPartialUpdateRequest.prototype.clearAuthorsList = function() {
  return this.setAuthorsList([]);
};


/**
 * repeated string categories = 4;
 * @return {!Array<string>}
 */
proto.dsg_example.example_bib_app.BookPartialUpdateRequest.prototype.getCategoriesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 4));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.dsg_example.example_bib_app.BookPartialUpdateRequest} returns this
 */
proto.dsg_example.example_bib_app.BookPartialUpdateRequest.prototype.setCategoriesList = function(value) {
  return jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.dsg_example.example_bib_app.BookPartialUpdateRequest} returns this
 */
proto.dsg_example.example_bib_app.BookPartialUpdateRequest.prototype.addCategories = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.dsg_example.example_bib_app.BookPartialUpdateRequest} returns this
 */
proto.dsg_example.example_bib_app.BookPartialUpdateRequest.prototype.clearCategoriesList = function() {
  return this.setCategoriesList([]);
};


/**
 * optional string isbn = 5;
 * @return {string}
 */
proto.dsg_example.example_bib_app.BookPartialUpdateRequest.prototype.getIsbn = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.dsg_example.example_bib_app.BookPartialUpdateRequest} returns this
 */
proto.dsg_example.example_bib_app.BookPartialUpdateRequest.prototype.setIsbn = function(value) {
  return jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.dsg_example.example_bib_app.BookPartialUpdateRequest} returns this
 */
proto.dsg_example.example_bib_app.BookPartialUpdateRequest.prototype.clearIsbn = function() {
  return jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.dsg_example.example_bib_app.BookPartialUpdateRequest.prototype.hasIsbn = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional string publisher = 6;
 * @return {string}
 */
proto.dsg_example.example_bib_app.BookPartialUpdateRequest.prototype.getPublisher = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.dsg_example.example_bib_app.BookPartialUpdateRequest} returns this
 */
proto.dsg_example.example_bib_app.BookPartialUpdateRequest.prototype.setPublisher = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string publication_date = 7;
 * @return {string}
 */
proto.dsg_example.example_bib_app.BookPartialUpdateRequest.prototype.getPublicationDate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.dsg_example.example_bib_app.BookPartialUpdateRequest} returns this
 */
proto.dsg_example.example_bib_app.BookPartialUpdateRequest.prototype.setPublicationDate = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * repeated string _partial_update_fields = 8;
 * @return {!Array<string>}
 */
proto.dsg_example.example_bib_app.BookPartialUpdateRequest.prototype.getPartialUpdateFieldsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 8));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.dsg_example.example_bib_app.BookPartialUpdateRequest} returns this
 */
proto.dsg_example.example_bib_app.BookPartialUpdateRequest.prototype.setPartialUpdateFieldsList = function(value) {
  return jspb.Message.setField(this, 8, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.dsg_example.example_bib_app.BookPartialUpdateRequest} returns this
 */
proto.dsg_example.example_bib_app.BookPartialUpdateRequest.prototype.addPartialUpdateFields = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 8, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.dsg_example.example_bib_app.BookPartialUpdateRequest} returns this
 */
proto.dsg_example.example_bib_app.BookPartialUpdateRequest.prototype.clearPartialUpdateFieldsList = function() {
  return this.setPartialUpdateFieldsList([]);
};


