# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from example_bib_app.grpc import example_bib_app_pb2 as example__bib__app_dot_grpc_dot_example__bib__app__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class AuthorControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/dsg_example.example_bib_app.AuthorController/Create',
                request_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.AuthorRequest.SerializeToString,
                response_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.AuthorResponse.FromString,
                )
        self.Destroy = channel.unary_unary(
                '/dsg_example.example_bib_app.AuthorController/Destroy',
                request_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.AuthorDestroyRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.List = channel.unary_unary(
                '/dsg_example.example_bib_app.AuthorController/List',
                request_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.AuthorListRequest.SerializeToString,
                response_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.AuthorListResponse.FromString,
                )
        self.PartialUpdate = channel.unary_unary(
                '/dsg_example.example_bib_app.AuthorController/PartialUpdate',
                request_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.AuthorPartialUpdateRequest.SerializeToString,
                response_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.AuthorResponse.FromString,
                )
        self.Retrieve = channel.unary_unary(
                '/dsg_example.example_bib_app.AuthorController/Retrieve',
                request_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.AuthorRetrieveRequest.SerializeToString,
                response_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.AuthorResponse.FromString,
                )
        self.Update = channel.unary_unary(
                '/dsg_example.example_bib_app.AuthorController/Update',
                request_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.AuthorRequest.SerializeToString,
                response_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.AuthorResponse.FromString,
                )


class AuthorControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PartialUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthorControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.AuthorRequest.FromString,
                    response_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.AuthorResponse.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.AuthorDestroyRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.AuthorListRequest.FromString,
                    response_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.AuthorListResponse.SerializeToString,
            ),
            'PartialUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.PartialUpdate,
                    request_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.AuthorPartialUpdateRequest.FromString,
                    response_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.AuthorResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.AuthorRetrieveRequest.FromString,
                    response_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.AuthorResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.AuthorRequest.FromString,
                    response_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.AuthorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dsg_example.example_bib_app.AuthorController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AuthorController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dsg_example.example_bib_app.AuthorController/Create',
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.AuthorRequest.SerializeToString,
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.AuthorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dsg_example.example_bib_app.AuthorController/Destroy',
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.AuthorDestroyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dsg_example.example_bib_app.AuthorController/List',
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.AuthorListRequest.SerializeToString,
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.AuthorListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PartialUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dsg_example.example_bib_app.AuthorController/PartialUpdate',
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.AuthorPartialUpdateRequest.SerializeToString,
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.AuthorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dsg_example.example_bib_app.AuthorController/Retrieve',
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.AuthorRetrieveRequest.SerializeToString,
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.AuthorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dsg_example.example_bib_app.AuthorController/Update',
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.AuthorRequest.SerializeToString,
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.AuthorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class BookControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/dsg_example.example_bib_app.BookController/Create',
                request_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.BookRequest.SerializeToString,
                response_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.BookResponse.FromString,
                )
        self.Destroy = channel.unary_unary(
                '/dsg_example.example_bib_app.BookController/Destroy',
                request_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.BookDestroyRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.List = channel.unary_unary(
                '/dsg_example.example_bib_app.BookController/List',
                request_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.BookListRequest.SerializeToString,
                response_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.BookListResponse.FromString,
                )
        self.PartialUpdate = channel.unary_unary(
                '/dsg_example.example_bib_app.BookController/PartialUpdate',
                request_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.BookPartialUpdateRequest.SerializeToString,
                response_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.BookResponse.FromString,
                )
        self.Retrieve = channel.unary_unary(
                '/dsg_example.example_bib_app.BookController/Retrieve',
                request_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.BookRetrieveRequest.SerializeToString,
                response_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.BookResponse.FromString,
                )
        self.Stream = channel.unary_stream(
                '/dsg_example.example_bib_app.BookController/Stream',
                request_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.BookStreamRequest.SerializeToString,
                response_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.BookResponse.FromString,
                )
        self.StreamBooksByIDList = channel.stream_stream(
                '/dsg_example.example_bib_app.BookController/StreamBooksByIDList',
                request_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.BookStreamBooksByIDListRequest.SerializeToString,
                response_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.BookStreamBooksByIDListResponse.FromString,
                )
        self.Update = channel.unary_unary(
                '/dsg_example.example_bib_app.BookController/Update',
                request_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.BookRequest.SerializeToString,
                response_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.BookResponse.FromString,
                )
        self.UpdateImage = channel.stream_unary(
                '/dsg_example.example_bib_app.BookController/UpdateImage',
                request_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.FileChunk.SerializeToString,
                response_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.UploadStatus.FromString,
                )


class BookControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PartialUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamBooksByIDList(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateImage(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.BookRequest.FromString,
                    response_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.BookResponse.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.BookDestroyRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.BookListRequest.FromString,
                    response_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.BookListResponse.SerializeToString,
            ),
            'PartialUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.PartialUpdate,
                    request_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.BookPartialUpdateRequest.FromString,
                    response_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.BookResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.BookRetrieveRequest.FromString,
                    response_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.BookResponse.SerializeToString,
            ),
            'Stream': grpc.unary_stream_rpc_method_handler(
                    servicer.Stream,
                    request_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.BookStreamRequest.FromString,
                    response_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.BookResponse.SerializeToString,
            ),
            'StreamBooksByIDList': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamBooksByIDList,
                    request_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.BookStreamBooksByIDListRequest.FromString,
                    response_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.BookStreamBooksByIDListResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.BookRequest.FromString,
                    response_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.BookResponse.SerializeToString,
            ),
            'UpdateImage': grpc.stream_unary_rpc_method_handler(
                    servicer.UpdateImage,
                    request_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.FileChunk.FromString,
                    response_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.UploadStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dsg_example.example_bib_app.BookController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BookController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dsg_example.example_bib_app.BookController/Create',
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.BookRequest.SerializeToString,
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.BookResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dsg_example.example_bib_app.BookController/Destroy',
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.BookDestroyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dsg_example.example_bib_app.BookController/List',
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.BookListRequest.SerializeToString,
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.BookListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PartialUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dsg_example.example_bib_app.BookController/PartialUpdate',
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.BookPartialUpdateRequest.SerializeToString,
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.BookResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dsg_example.example_bib_app.BookController/Retrieve',
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.BookRetrieveRequest.SerializeToString,
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.BookResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Stream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/dsg_example.example_bib_app.BookController/Stream',
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.BookStreamRequest.SerializeToString,
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.BookResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamBooksByIDList(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/dsg_example.example_bib_app.BookController/StreamBooksByIDList',
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.BookStreamBooksByIDListRequest.SerializeToString,
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.BookStreamBooksByIDListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dsg_example.example_bib_app.BookController/Update',
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.BookRequest.SerializeToString,
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.BookResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateImage(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/dsg_example.example_bib_app.BookController/UpdateImage',
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.FileChunk.SerializeToString,
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.UploadStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class JournalControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/dsg_example.example_bib_app.JournalController/Create',
                request_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.JournalRequest.SerializeToString,
                response_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.JournalResponse.FromString,
                )
        self.Destroy = channel.unary_unary(
                '/dsg_example.example_bib_app.JournalController/Destroy',
                request_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.JournalDestroyRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.List = channel.unary_unary(
                '/dsg_example.example_bib_app.JournalController/List',
                request_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.JournalListRequest.SerializeToString,
                response_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.JournalListResponse.FromString,
                )
        self.PartialUpdate = channel.unary_unary(
                '/dsg_example.example_bib_app.JournalController/PartialUpdate',
                request_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.JournalPartialUpdateRequest.SerializeToString,
                response_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.JournalResponse.FromString,
                )
        self.Retrieve = channel.unary_unary(
                '/dsg_example.example_bib_app.JournalController/Retrieve',
                request_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.JournalRetrieveRequest.SerializeToString,
                response_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.JournalResponse.FromString,
                )
        self.Update = channel.unary_unary(
                '/dsg_example.example_bib_app.JournalController/Update',
                request_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.JournalRequest.SerializeToString,
                response_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.JournalResponse.FromString,
                )


class JournalControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PartialUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JournalControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.JournalRequest.FromString,
                    response_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.JournalResponse.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.JournalDestroyRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.JournalListRequest.FromString,
                    response_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.JournalListResponse.SerializeToString,
            ),
            'PartialUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.PartialUpdate,
                    request_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.JournalPartialUpdateRequest.FromString,
                    response_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.JournalResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.JournalRetrieveRequest.FromString,
                    response_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.JournalResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.JournalRequest.FromString,
                    response_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.JournalResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dsg_example.example_bib_app.JournalController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class JournalController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dsg_example.example_bib_app.JournalController/Create',
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.JournalRequest.SerializeToString,
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.JournalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dsg_example.example_bib_app.JournalController/Destroy',
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.JournalDestroyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dsg_example.example_bib_app.JournalController/List',
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.JournalListRequest.SerializeToString,
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.JournalListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PartialUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dsg_example.example_bib_app.JournalController/PartialUpdate',
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.JournalPartialUpdateRequest.SerializeToString,
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.JournalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dsg_example.example_bib_app.JournalController/Retrieve',
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.JournalRetrieveRequest.SerializeToString,
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.JournalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dsg_example.example_bib_app.JournalController/Update',
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.JournalRequest.SerializeToString,
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.JournalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class PublicationCategoryControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/dsg_example.example_bib_app.PublicationCategoryController/Create',
                request_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublicationCategoryRequest.SerializeToString,
                response_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublicationCategoryResponse.FromString,
                )
        self.Destroy = channel.unary_unary(
                '/dsg_example.example_bib_app.PublicationCategoryController/Destroy',
                request_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublicationCategoryDestroyRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.List = channel.unary_unary(
                '/dsg_example.example_bib_app.PublicationCategoryController/List',
                request_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublicationCategoryListRequest.SerializeToString,
                response_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublicationCategoryListResponse.FromString,
                )
        self.PartialUpdate = channel.unary_unary(
                '/dsg_example.example_bib_app.PublicationCategoryController/PartialUpdate',
                request_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublicationCategoryPartialUpdateRequest.SerializeToString,
                response_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublicationCategoryResponse.FromString,
                )
        self.Retrieve = channel.unary_unary(
                '/dsg_example.example_bib_app.PublicationCategoryController/Retrieve',
                request_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublicationCategoryRetrieveRequest.SerializeToString,
                response_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublicationCategoryResponse.FromString,
                )
        self.Update = channel.unary_unary(
                '/dsg_example.example_bib_app.PublicationCategoryController/Update',
                request_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublicationCategoryRequest.SerializeToString,
                response_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublicationCategoryResponse.FromString,
                )


class PublicationCategoryControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PartialUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PublicationCategoryControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublicationCategoryRequest.FromString,
                    response_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublicationCategoryResponse.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublicationCategoryDestroyRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublicationCategoryListRequest.FromString,
                    response_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublicationCategoryListResponse.SerializeToString,
            ),
            'PartialUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.PartialUpdate,
                    request_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublicationCategoryPartialUpdateRequest.FromString,
                    response_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublicationCategoryResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublicationCategoryRetrieveRequest.FromString,
                    response_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublicationCategoryResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublicationCategoryRequest.FromString,
                    response_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublicationCategoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dsg_example.example_bib_app.PublicationCategoryController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PublicationCategoryController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dsg_example.example_bib_app.PublicationCategoryController/Create',
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublicationCategoryRequest.SerializeToString,
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublicationCategoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dsg_example.example_bib_app.PublicationCategoryController/Destroy',
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublicationCategoryDestroyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dsg_example.example_bib_app.PublicationCategoryController/List',
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublicationCategoryListRequest.SerializeToString,
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublicationCategoryListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PartialUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dsg_example.example_bib_app.PublicationCategoryController/PartialUpdate',
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublicationCategoryPartialUpdateRequest.SerializeToString,
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublicationCategoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dsg_example.example_bib_app.PublicationCategoryController/Retrieve',
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublicationCategoryRetrieveRequest.SerializeToString,
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublicationCategoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dsg_example.example_bib_app.PublicationCategoryController/Update',
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublicationCategoryRequest.SerializeToString,
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublicationCategoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class PublisherControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/dsg_example.example_bib_app.PublisherController/Create',
                request_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublisherRequest.SerializeToString,
                response_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublisherResponse.FromString,
                )
        self.Destroy = channel.unary_unary(
                '/dsg_example.example_bib_app.PublisherController/Destroy',
                request_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublisherDestroyRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.List = channel.unary_unary(
                '/dsg_example.example_bib_app.PublisherController/List',
                request_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublisherListRequest.SerializeToString,
                response_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublisherListResponse.FromString,
                )
        self.PartialUpdate = channel.unary_unary(
                '/dsg_example.example_bib_app.PublisherController/PartialUpdate',
                request_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublisherPartialUpdateRequest.SerializeToString,
                response_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublisherResponse.FromString,
                )
        self.Retrieve = channel.unary_unary(
                '/dsg_example.example_bib_app.PublisherController/Retrieve',
                request_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublisherRetrieveRequest.SerializeToString,
                response_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublisherResponse.FromString,
                )
        self.Update = channel.unary_unary(
                '/dsg_example.example_bib_app.PublisherController/Update',
                request_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublisherRequest.SerializeToString,
                response_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublisherResponse.FromString,
                )


class PublisherControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PartialUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PublisherControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublisherRequest.FromString,
                    response_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublisherResponse.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublisherDestroyRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublisherListRequest.FromString,
                    response_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublisherListResponse.SerializeToString,
            ),
            'PartialUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.PartialUpdate,
                    request_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublisherPartialUpdateRequest.FromString,
                    response_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublisherResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublisherRetrieveRequest.FromString,
                    response_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublisherResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublisherRequest.FromString,
                    response_serializer=example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublisherResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dsg_example.example_bib_app.PublisherController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PublisherController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dsg_example.example_bib_app.PublisherController/Create',
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublisherRequest.SerializeToString,
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublisherResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dsg_example.example_bib_app.PublisherController/Destroy',
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublisherDestroyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dsg_example.example_bib_app.PublisherController/List',
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublisherListRequest.SerializeToString,
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublisherListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PartialUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dsg_example.example_bib_app.PublisherController/PartialUpdate',
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublisherPartialUpdateRequest.SerializeToString,
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublisherResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dsg_example.example_bib_app.PublisherController/Retrieve',
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublisherRetrieveRequest.SerializeToString,
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublisherResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dsg_example.example_bib_app.PublisherController/Update',
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublisherRequest.SerializeToString,
            example__bib__app_dot_grpc_dot_example__bib__app__pb2.PublisherResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
