/**
 * @fileoverview gRPC-Web generated client stub for dsg_example.example_bib_app
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.21.11
// source: example_bib_app.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js')
const proto = {};
proto.dsg_example = {};
proto.dsg_example.example_bib_app = require('./example_bib_app_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.dsg_example.example_bib_app.AuthorControllerClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.dsg_example.example_bib_app.AuthorControllerPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.dsg_example.example_bib_app.AuthorRequest,
 *   !proto.dsg_example.example_bib_app.AuthorResponse>}
 */
const methodDescriptor_AuthorController_Create = new grpc.web.MethodDescriptor(
  '/dsg_example.example_bib_app.AuthorController/Create',
  grpc.web.MethodType.UNARY,
  proto.dsg_example.example_bib_app.AuthorRequest,
  proto.dsg_example.example_bib_app.AuthorResponse,
  /**
   * @param {!proto.dsg_example.example_bib_app.AuthorRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.dsg_example.example_bib_app.AuthorResponse.deserializeBinary
);


/**
 * @param {!proto.dsg_example.example_bib_app.AuthorRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.dsg_example.example_bib_app.AuthorResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.dsg_example.example_bib_app.AuthorResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.dsg_example.example_bib_app.AuthorControllerClient.prototype.create =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/dsg_example.example_bib_app.AuthorController/Create',
      request,
      metadata || {},
      methodDescriptor_AuthorController_Create,
      callback);
};


/**
 * @param {!proto.dsg_example.example_bib_app.AuthorRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.dsg_example.example_bib_app.AuthorResponse>}
 *     Promise that resolves to the response
 */
proto.dsg_example.example_bib_app.AuthorControllerPromiseClient.prototype.create =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/dsg_example.example_bib_app.AuthorController/Create',
      request,
      metadata || {},
      methodDescriptor_AuthorController_Create);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.dsg_example.example_bib_app.AuthorDestroyRequest,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_AuthorController_Destroy = new grpc.web.MethodDescriptor(
  '/dsg_example.example_bib_app.AuthorController/Destroy',
  grpc.web.MethodType.UNARY,
  proto.dsg_example.example_bib_app.AuthorDestroyRequest,
  google_protobuf_empty_pb.Empty,
  /**
   * @param {!proto.dsg_example.example_bib_app.AuthorDestroyRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_protobuf_empty_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.dsg_example.example_bib_app.AuthorDestroyRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.dsg_example.example_bib_app.AuthorControllerClient.prototype.destroy =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/dsg_example.example_bib_app.AuthorController/Destroy',
      request,
      metadata || {},
      methodDescriptor_AuthorController_Destroy,
      callback);
};


/**
 * @param {!proto.dsg_example.example_bib_app.AuthorDestroyRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.dsg_example.example_bib_app.AuthorControllerPromiseClient.prototype.destroy =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/dsg_example.example_bib_app.AuthorController/Destroy',
      request,
      metadata || {},
      methodDescriptor_AuthorController_Destroy);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.dsg_example.example_bib_app.AuthorListRequest,
 *   !proto.dsg_example.example_bib_app.AuthorListResponse>}
 */
const methodDescriptor_AuthorController_List = new grpc.web.MethodDescriptor(
  '/dsg_example.example_bib_app.AuthorController/List',
  grpc.web.MethodType.UNARY,
  proto.dsg_example.example_bib_app.AuthorListRequest,
  proto.dsg_example.example_bib_app.AuthorListResponse,
  /**
   * @param {!proto.dsg_example.example_bib_app.AuthorListRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.dsg_example.example_bib_app.AuthorListResponse.deserializeBinary
);


/**
 * @param {!proto.dsg_example.example_bib_app.AuthorListRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.dsg_example.example_bib_app.AuthorListResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.dsg_example.example_bib_app.AuthorListResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.dsg_example.example_bib_app.AuthorControllerClient.prototype.list =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/dsg_example.example_bib_app.AuthorController/List',
      request,
      metadata || {},
      methodDescriptor_AuthorController_List,
      callback);
};


/**
 * @param {!proto.dsg_example.example_bib_app.AuthorListRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.dsg_example.example_bib_app.AuthorListResponse>}
 *     Promise that resolves to the response
 */
proto.dsg_example.example_bib_app.AuthorControllerPromiseClient.prototype.list =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/dsg_example.example_bib_app.AuthorController/List',
      request,
      metadata || {},
      methodDescriptor_AuthorController_List);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.dsg_example.example_bib_app.AuthorPartialUpdateRequest,
 *   !proto.dsg_example.example_bib_app.AuthorResponse>}
 */
const methodDescriptor_AuthorController_PartialUpdate = new grpc.web.MethodDescriptor(
  '/dsg_example.example_bib_app.AuthorController/PartialUpdate',
  grpc.web.MethodType.UNARY,
  proto.dsg_example.example_bib_app.AuthorPartialUpdateRequest,
  proto.dsg_example.example_bib_app.AuthorResponse,
  /**
   * @param {!proto.dsg_example.example_bib_app.AuthorPartialUpdateRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.dsg_example.example_bib_app.AuthorResponse.deserializeBinary
);


/**
 * @param {!proto.dsg_example.example_bib_app.AuthorPartialUpdateRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.dsg_example.example_bib_app.AuthorResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.dsg_example.example_bib_app.AuthorResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.dsg_example.example_bib_app.AuthorControllerClient.prototype.partialUpdate =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/dsg_example.example_bib_app.AuthorController/PartialUpdate',
      request,
      metadata || {},
      methodDescriptor_AuthorController_PartialUpdate,
      callback);
};


/**
 * @param {!proto.dsg_example.example_bib_app.AuthorPartialUpdateRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.dsg_example.example_bib_app.AuthorResponse>}
 *     Promise that resolves to the response
 */
proto.dsg_example.example_bib_app.AuthorControllerPromiseClient.prototype.partialUpdate =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/dsg_example.example_bib_app.AuthorController/PartialUpdate',
      request,
      metadata || {},
      methodDescriptor_AuthorController_PartialUpdate);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.dsg_example.example_bib_app.AuthorRetrieveRequest,
 *   !proto.dsg_example.example_bib_app.AuthorResponse>}
 */
const methodDescriptor_AuthorController_Retrieve = new grpc.web.MethodDescriptor(
  '/dsg_example.example_bib_app.AuthorController/Retrieve',
  grpc.web.MethodType.UNARY,
  proto.dsg_example.example_bib_app.AuthorRetrieveRequest,
  proto.dsg_example.example_bib_app.AuthorResponse,
  /**
   * @param {!proto.dsg_example.example_bib_app.AuthorRetrieveRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.dsg_example.example_bib_app.AuthorResponse.deserializeBinary
);


/**
 * @param {!proto.dsg_example.example_bib_app.AuthorRetrieveRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.dsg_example.example_bib_app.AuthorResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.dsg_example.example_bib_app.AuthorResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.dsg_example.example_bib_app.AuthorControllerClient.prototype.retrieve =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/dsg_example.example_bib_app.AuthorController/Retrieve',
      request,
      metadata || {},
      methodDescriptor_AuthorController_Retrieve,
      callback);
};


/**
 * @param {!proto.dsg_example.example_bib_app.AuthorRetrieveRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.dsg_example.example_bib_app.AuthorResponse>}
 *     Promise that resolves to the response
 */
proto.dsg_example.example_bib_app.AuthorControllerPromiseClient.prototype.retrieve =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/dsg_example.example_bib_app.AuthorController/Retrieve',
      request,
      metadata || {},
      methodDescriptor_AuthorController_Retrieve);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.dsg_example.example_bib_app.AuthorRequest,
 *   !proto.dsg_example.example_bib_app.AuthorResponse>}
 */
const methodDescriptor_AuthorController_Update = new grpc.web.MethodDescriptor(
  '/dsg_example.example_bib_app.AuthorController/Update',
  grpc.web.MethodType.UNARY,
  proto.dsg_example.example_bib_app.AuthorRequest,
  proto.dsg_example.example_bib_app.AuthorResponse,
  /**
   * @param {!proto.dsg_example.example_bib_app.AuthorRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.dsg_example.example_bib_app.AuthorResponse.deserializeBinary
);


/**
 * @param {!proto.dsg_example.example_bib_app.AuthorRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.dsg_example.example_bib_app.AuthorResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.dsg_example.example_bib_app.AuthorResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.dsg_example.example_bib_app.AuthorControllerClient.prototype.update =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/dsg_example.example_bib_app.AuthorController/Update',
      request,
      metadata || {},
      methodDescriptor_AuthorController_Update,
      callback);
};


/**
 * @param {!proto.dsg_example.example_bib_app.AuthorRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.dsg_example.example_bib_app.AuthorResponse>}
 *     Promise that resolves to the response
 */
proto.dsg_example.example_bib_app.AuthorControllerPromiseClient.prototype.update =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/dsg_example.example_bib_app.AuthorController/Update',
      request,
      metadata || {},
      methodDescriptor_AuthorController_Update);
};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.dsg_example.example_bib_app.BookControllerClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.dsg_example.example_bib_app.BookControllerPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.dsg_example.example_bib_app.BookRequest,
 *   !proto.dsg_example.example_bib_app.BookResponse>}
 */
const methodDescriptor_BookController_Create = new grpc.web.MethodDescriptor(
  '/dsg_example.example_bib_app.BookController/Create',
  grpc.web.MethodType.UNARY,
  proto.dsg_example.example_bib_app.BookRequest,
  proto.dsg_example.example_bib_app.BookResponse,
  /**
   * @param {!proto.dsg_example.example_bib_app.BookRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.dsg_example.example_bib_app.BookResponse.deserializeBinary
);


/**
 * @param {!proto.dsg_example.example_bib_app.BookRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.dsg_example.example_bib_app.BookResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.dsg_example.example_bib_app.BookResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.dsg_example.example_bib_app.BookControllerClient.prototype.create =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/dsg_example.example_bib_app.BookController/Create',
      request,
      metadata || {},
      methodDescriptor_BookController_Create,
      callback);
};


/**
 * @param {!proto.dsg_example.example_bib_app.BookRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.dsg_example.example_bib_app.BookResponse>}
 *     Promise that resolves to the response
 */
proto.dsg_example.example_bib_app.BookControllerPromiseClient.prototype.create =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/dsg_example.example_bib_app.BookController/Create',
      request,
      metadata || {},
      methodDescriptor_BookController_Create);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.dsg_example.example_bib_app.BookDestroyRequest,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_BookController_Destroy = new grpc.web.MethodDescriptor(
  '/dsg_example.example_bib_app.BookController/Destroy',
  grpc.web.MethodType.UNARY,
  proto.dsg_example.example_bib_app.BookDestroyRequest,
  google_protobuf_empty_pb.Empty,
  /**
   * @param {!proto.dsg_example.example_bib_app.BookDestroyRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_protobuf_empty_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.dsg_example.example_bib_app.BookDestroyRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.dsg_example.example_bib_app.BookControllerClient.prototype.destroy =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/dsg_example.example_bib_app.BookController/Destroy',
      request,
      metadata || {},
      methodDescriptor_BookController_Destroy,
      callback);
};


/**
 * @param {!proto.dsg_example.example_bib_app.BookDestroyRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.dsg_example.example_bib_app.BookControllerPromiseClient.prototype.destroy =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/dsg_example.example_bib_app.BookController/Destroy',
      request,
      metadata || {},
      methodDescriptor_BookController_Destroy);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.dsg_example.example_bib_app.BookListRequest,
 *   !proto.dsg_example.example_bib_app.BookListResponse>}
 */
const methodDescriptor_BookController_List = new grpc.web.MethodDescriptor(
  '/dsg_example.example_bib_app.BookController/List',
  grpc.web.MethodType.UNARY,
  proto.dsg_example.example_bib_app.BookListRequest,
  proto.dsg_example.example_bib_app.BookListResponse,
  /**
   * @param {!proto.dsg_example.example_bib_app.BookListRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.dsg_example.example_bib_app.BookListResponse.deserializeBinary
);


/**
 * @param {!proto.dsg_example.example_bib_app.BookListRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.dsg_example.example_bib_app.BookListResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.dsg_example.example_bib_app.BookListResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.dsg_example.example_bib_app.BookControllerClient.prototype.list =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/dsg_example.example_bib_app.BookController/List',
      request,
      metadata || {},
      methodDescriptor_BookController_List,
      callback);
};


/**
 * @param {!proto.dsg_example.example_bib_app.BookListRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.dsg_example.example_bib_app.BookListResponse>}
 *     Promise that resolves to the response
 */
proto.dsg_example.example_bib_app.BookControllerPromiseClient.prototype.list =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/dsg_example.example_bib_app.BookController/List',
      request,
      metadata || {},
      methodDescriptor_BookController_List);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.dsg_example.example_bib_app.BookPartialUpdateRequest,
 *   !proto.dsg_example.example_bib_app.BookResponse>}
 */
const methodDescriptor_BookController_PartialUpdate = new grpc.web.MethodDescriptor(
  '/dsg_example.example_bib_app.BookController/PartialUpdate',
  grpc.web.MethodType.UNARY,
  proto.dsg_example.example_bib_app.BookPartialUpdateRequest,
  proto.dsg_example.example_bib_app.BookResponse,
  /**
   * @param {!proto.dsg_example.example_bib_app.BookPartialUpdateRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.dsg_example.example_bib_app.BookResponse.deserializeBinary
);


/**
 * @param {!proto.dsg_example.example_bib_app.BookPartialUpdateRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.dsg_example.example_bib_app.BookResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.dsg_example.example_bib_app.BookResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.dsg_example.example_bib_app.BookControllerClient.prototype.partialUpdate =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/dsg_example.example_bib_app.BookController/PartialUpdate',
      request,
      metadata || {},
      methodDescriptor_BookController_PartialUpdate,
      callback);
};


/**
 * @param {!proto.dsg_example.example_bib_app.BookPartialUpdateRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.dsg_example.example_bib_app.BookResponse>}
 *     Promise that resolves to the response
 */
proto.dsg_example.example_bib_app.BookControllerPromiseClient.prototype.partialUpdate =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/dsg_example.example_bib_app.BookController/PartialUpdate',
      request,
      metadata || {},
      methodDescriptor_BookController_PartialUpdate);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.dsg_example.example_bib_app.BookRetrieveRequest,
 *   !proto.dsg_example.example_bib_app.BookResponse>}
 */
const methodDescriptor_BookController_Retrieve = new grpc.web.MethodDescriptor(
  '/dsg_example.example_bib_app.BookController/Retrieve',
  grpc.web.MethodType.UNARY,
  proto.dsg_example.example_bib_app.BookRetrieveRequest,
  proto.dsg_example.example_bib_app.BookResponse,
  /**
   * @param {!proto.dsg_example.example_bib_app.BookRetrieveRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.dsg_example.example_bib_app.BookResponse.deserializeBinary
);


/**
 * @param {!proto.dsg_example.example_bib_app.BookRetrieveRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.dsg_example.example_bib_app.BookResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.dsg_example.example_bib_app.BookResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.dsg_example.example_bib_app.BookControllerClient.prototype.retrieve =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/dsg_example.example_bib_app.BookController/Retrieve',
      request,
      metadata || {},
      methodDescriptor_BookController_Retrieve,
      callback);
};


/**
 * @param {!proto.dsg_example.example_bib_app.BookRetrieveRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.dsg_example.example_bib_app.BookResponse>}
 *     Promise that resolves to the response
 */
proto.dsg_example.example_bib_app.BookControllerPromiseClient.prototype.retrieve =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/dsg_example.example_bib_app.BookController/Retrieve',
      request,
      metadata || {},
      methodDescriptor_BookController_Retrieve);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.dsg_example.example_bib_app.BookStreamRequest,
 *   !proto.dsg_example.example_bib_app.BookResponse>}
 */
const methodDescriptor_BookController_Stream = new grpc.web.MethodDescriptor(
  '/dsg_example.example_bib_app.BookController/Stream',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.dsg_example.example_bib_app.BookStreamRequest,
  proto.dsg_example.example_bib_app.BookResponse,
  /**
   * @param {!proto.dsg_example.example_bib_app.BookStreamRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.dsg_example.example_bib_app.BookResponse.deserializeBinary
);


/**
 * @param {!proto.dsg_example.example_bib_app.BookStreamRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.dsg_example.example_bib_app.BookResponse>}
 *     The XHR Node Readable Stream
 */
proto.dsg_example.example_bib_app.BookControllerClient.prototype.stream =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/dsg_example.example_bib_app.BookController/Stream',
      request,
      metadata || {},
      methodDescriptor_BookController_Stream);
};


/**
 * @param {!proto.dsg_example.example_bib_app.BookStreamRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.dsg_example.example_bib_app.BookResponse>}
 *     The XHR Node Readable Stream
 */
proto.dsg_example.example_bib_app.BookControllerPromiseClient.prototype.stream =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/dsg_example.example_bib_app.BookController/Stream',
      request,
      metadata || {},
      methodDescriptor_BookController_Stream);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.dsg_example.example_bib_app.BookRequest,
 *   !proto.dsg_example.example_bib_app.BookResponse>}
 */
const methodDescriptor_BookController_Update = new grpc.web.MethodDescriptor(
  '/dsg_example.example_bib_app.BookController/Update',
  grpc.web.MethodType.UNARY,
  proto.dsg_example.example_bib_app.BookRequest,
  proto.dsg_example.example_bib_app.BookResponse,
  /**
   * @param {!proto.dsg_example.example_bib_app.BookRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.dsg_example.example_bib_app.BookResponse.deserializeBinary
);


/**
 * @param {!proto.dsg_example.example_bib_app.BookRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.dsg_example.example_bib_app.BookResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.dsg_example.example_bib_app.BookResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.dsg_example.example_bib_app.BookControllerClient.prototype.update =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/dsg_example.example_bib_app.BookController/Update',
      request,
      metadata || {},
      methodDescriptor_BookController_Update,
      callback);
};


/**
 * @param {!proto.dsg_example.example_bib_app.BookRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.dsg_example.example_bib_app.BookResponse>}
 *     Promise that resolves to the response
 */
proto.dsg_example.example_bib_app.BookControllerPromiseClient.prototype.update =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/dsg_example.example_bib_app.BookController/Update',
      request,
      metadata || {},
      methodDescriptor_BookController_Update);
};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.dsg_example.example_bib_app.JournalControllerClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.dsg_example.example_bib_app.JournalControllerPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.dsg_example.example_bib_app.JournalRequest,
 *   !proto.dsg_example.example_bib_app.JournalResponse>}
 */
const methodDescriptor_JournalController_Create = new grpc.web.MethodDescriptor(
  '/dsg_example.example_bib_app.JournalController/Create',
  grpc.web.MethodType.UNARY,
  proto.dsg_example.example_bib_app.JournalRequest,
  proto.dsg_example.example_bib_app.JournalResponse,
  /**
   * @param {!proto.dsg_example.example_bib_app.JournalRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.dsg_example.example_bib_app.JournalResponse.deserializeBinary
);


/**
 * @param {!proto.dsg_example.example_bib_app.JournalRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.dsg_example.example_bib_app.JournalResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.dsg_example.example_bib_app.JournalResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.dsg_example.example_bib_app.JournalControllerClient.prototype.create =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/dsg_example.example_bib_app.JournalController/Create',
      request,
      metadata || {},
      methodDescriptor_JournalController_Create,
      callback);
};


/**
 * @param {!proto.dsg_example.example_bib_app.JournalRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.dsg_example.example_bib_app.JournalResponse>}
 *     Promise that resolves to the response
 */
proto.dsg_example.example_bib_app.JournalControllerPromiseClient.prototype.create =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/dsg_example.example_bib_app.JournalController/Create',
      request,
      metadata || {},
      methodDescriptor_JournalController_Create);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.dsg_example.example_bib_app.JournalDestroyRequest,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_JournalController_Destroy = new grpc.web.MethodDescriptor(
  '/dsg_example.example_bib_app.JournalController/Destroy',
  grpc.web.MethodType.UNARY,
  proto.dsg_example.example_bib_app.JournalDestroyRequest,
  google_protobuf_empty_pb.Empty,
  /**
   * @param {!proto.dsg_example.example_bib_app.JournalDestroyRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_protobuf_empty_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.dsg_example.example_bib_app.JournalDestroyRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.dsg_example.example_bib_app.JournalControllerClient.prototype.destroy =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/dsg_example.example_bib_app.JournalController/Destroy',
      request,
      metadata || {},
      methodDescriptor_JournalController_Destroy,
      callback);
};


/**
 * @param {!proto.dsg_example.example_bib_app.JournalDestroyRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.dsg_example.example_bib_app.JournalControllerPromiseClient.prototype.destroy =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/dsg_example.example_bib_app.JournalController/Destroy',
      request,
      metadata || {},
      methodDescriptor_JournalController_Destroy);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.dsg_example.example_bib_app.JournalListRequest,
 *   !proto.dsg_example.example_bib_app.JournalListResponse>}
 */
const methodDescriptor_JournalController_List = new grpc.web.MethodDescriptor(
  '/dsg_example.example_bib_app.JournalController/List',
  grpc.web.MethodType.UNARY,
  proto.dsg_example.example_bib_app.JournalListRequest,
  proto.dsg_example.example_bib_app.JournalListResponse,
  /**
   * @param {!proto.dsg_example.example_bib_app.JournalListRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.dsg_example.example_bib_app.JournalListResponse.deserializeBinary
);


/**
 * @param {!proto.dsg_example.example_bib_app.JournalListRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.dsg_example.example_bib_app.JournalListResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.dsg_example.example_bib_app.JournalListResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.dsg_example.example_bib_app.JournalControllerClient.prototype.list =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/dsg_example.example_bib_app.JournalController/List',
      request,
      metadata || {},
      methodDescriptor_JournalController_List,
      callback);
};


/**
 * @param {!proto.dsg_example.example_bib_app.JournalListRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.dsg_example.example_bib_app.JournalListResponse>}
 *     Promise that resolves to the response
 */
proto.dsg_example.example_bib_app.JournalControllerPromiseClient.prototype.list =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/dsg_example.example_bib_app.JournalController/List',
      request,
      metadata || {},
      methodDescriptor_JournalController_List);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.dsg_example.example_bib_app.JournalPartialUpdateRequest,
 *   !proto.dsg_example.example_bib_app.JournalResponse>}
 */
const methodDescriptor_JournalController_PartialUpdate = new grpc.web.MethodDescriptor(
  '/dsg_example.example_bib_app.JournalController/PartialUpdate',
  grpc.web.MethodType.UNARY,
  proto.dsg_example.example_bib_app.JournalPartialUpdateRequest,
  proto.dsg_example.example_bib_app.JournalResponse,
  /**
   * @param {!proto.dsg_example.example_bib_app.JournalPartialUpdateRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.dsg_example.example_bib_app.JournalResponse.deserializeBinary
);


/**
 * @param {!proto.dsg_example.example_bib_app.JournalPartialUpdateRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.dsg_example.example_bib_app.JournalResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.dsg_example.example_bib_app.JournalResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.dsg_example.example_bib_app.JournalControllerClient.prototype.partialUpdate =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/dsg_example.example_bib_app.JournalController/PartialUpdate',
      request,
      metadata || {},
      methodDescriptor_JournalController_PartialUpdate,
      callback);
};


/**
 * @param {!proto.dsg_example.example_bib_app.JournalPartialUpdateRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.dsg_example.example_bib_app.JournalResponse>}
 *     Promise that resolves to the response
 */
proto.dsg_example.example_bib_app.JournalControllerPromiseClient.prototype.partialUpdate =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/dsg_example.example_bib_app.JournalController/PartialUpdate',
      request,
      metadata || {},
      methodDescriptor_JournalController_PartialUpdate);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.dsg_example.example_bib_app.JournalRetrieveRequest,
 *   !proto.dsg_example.example_bib_app.JournalResponse>}
 */
const methodDescriptor_JournalController_Retrieve = new grpc.web.MethodDescriptor(
  '/dsg_example.example_bib_app.JournalController/Retrieve',
  grpc.web.MethodType.UNARY,
  proto.dsg_example.example_bib_app.JournalRetrieveRequest,
  proto.dsg_example.example_bib_app.JournalResponse,
  /**
   * @param {!proto.dsg_example.example_bib_app.JournalRetrieveRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.dsg_example.example_bib_app.JournalResponse.deserializeBinary
);


/**
 * @param {!proto.dsg_example.example_bib_app.JournalRetrieveRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.dsg_example.example_bib_app.JournalResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.dsg_example.example_bib_app.JournalResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.dsg_example.example_bib_app.JournalControllerClient.prototype.retrieve =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/dsg_example.example_bib_app.JournalController/Retrieve',
      request,
      metadata || {},
      methodDescriptor_JournalController_Retrieve,
      callback);
};


/**
 * @param {!proto.dsg_example.example_bib_app.JournalRetrieveRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.dsg_example.example_bib_app.JournalResponse>}
 *     Promise that resolves to the response
 */
proto.dsg_example.example_bib_app.JournalControllerPromiseClient.prototype.retrieve =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/dsg_example.example_bib_app.JournalController/Retrieve',
      request,
      metadata || {},
      methodDescriptor_JournalController_Retrieve);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.dsg_example.example_bib_app.JournalRequest,
 *   !proto.dsg_example.example_bib_app.JournalResponse>}
 */
const methodDescriptor_JournalController_Update = new grpc.web.MethodDescriptor(
  '/dsg_example.example_bib_app.JournalController/Update',
  grpc.web.MethodType.UNARY,
  proto.dsg_example.example_bib_app.JournalRequest,
  proto.dsg_example.example_bib_app.JournalResponse,
  /**
   * @param {!proto.dsg_example.example_bib_app.JournalRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.dsg_example.example_bib_app.JournalResponse.deserializeBinary
);


/**
 * @param {!proto.dsg_example.example_bib_app.JournalRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.dsg_example.example_bib_app.JournalResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.dsg_example.example_bib_app.JournalResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.dsg_example.example_bib_app.JournalControllerClient.prototype.update =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/dsg_example.example_bib_app.JournalController/Update',
      request,
      metadata || {},
      methodDescriptor_JournalController_Update,
      callback);
};


/**
 * @param {!proto.dsg_example.example_bib_app.JournalRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.dsg_example.example_bib_app.JournalResponse>}
 *     Promise that resolves to the response
 */
proto.dsg_example.example_bib_app.JournalControllerPromiseClient.prototype.update =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/dsg_example.example_bib_app.JournalController/Update',
      request,
      metadata || {},
      methodDescriptor_JournalController_Update);
};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.dsg_example.example_bib_app.PublicationCategoryControllerClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.dsg_example.example_bib_app.PublicationCategoryControllerPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.dsg_example.example_bib_app.PublicationCategoryRequest,
 *   !proto.dsg_example.example_bib_app.PublicationCategoryResponse>}
 */
const methodDescriptor_PublicationCategoryController_Create = new grpc.web.MethodDescriptor(
  '/dsg_example.example_bib_app.PublicationCategoryController/Create',
  grpc.web.MethodType.UNARY,
  proto.dsg_example.example_bib_app.PublicationCategoryRequest,
  proto.dsg_example.example_bib_app.PublicationCategoryResponse,
  /**
   * @param {!proto.dsg_example.example_bib_app.PublicationCategoryRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.dsg_example.example_bib_app.PublicationCategoryResponse.deserializeBinary
);


/**
 * @param {!proto.dsg_example.example_bib_app.PublicationCategoryRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.dsg_example.example_bib_app.PublicationCategoryResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.dsg_example.example_bib_app.PublicationCategoryResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.dsg_example.example_bib_app.PublicationCategoryControllerClient.prototype.create =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/dsg_example.example_bib_app.PublicationCategoryController/Create',
      request,
      metadata || {},
      methodDescriptor_PublicationCategoryController_Create,
      callback);
};


/**
 * @param {!proto.dsg_example.example_bib_app.PublicationCategoryRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.dsg_example.example_bib_app.PublicationCategoryResponse>}
 *     Promise that resolves to the response
 */
proto.dsg_example.example_bib_app.PublicationCategoryControllerPromiseClient.prototype.create =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/dsg_example.example_bib_app.PublicationCategoryController/Create',
      request,
      metadata || {},
      methodDescriptor_PublicationCategoryController_Create);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.dsg_example.example_bib_app.PublicationCategoryDestroyRequest,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_PublicationCategoryController_Destroy = new grpc.web.MethodDescriptor(
  '/dsg_example.example_bib_app.PublicationCategoryController/Destroy',
  grpc.web.MethodType.UNARY,
  proto.dsg_example.example_bib_app.PublicationCategoryDestroyRequest,
  google_protobuf_empty_pb.Empty,
  /**
   * @param {!proto.dsg_example.example_bib_app.PublicationCategoryDestroyRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_protobuf_empty_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.dsg_example.example_bib_app.PublicationCategoryDestroyRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.dsg_example.example_bib_app.PublicationCategoryControllerClient.prototype.destroy =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/dsg_example.example_bib_app.PublicationCategoryController/Destroy',
      request,
      metadata || {},
      methodDescriptor_PublicationCategoryController_Destroy,
      callback);
};


/**
 * @param {!proto.dsg_example.example_bib_app.PublicationCategoryDestroyRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.dsg_example.example_bib_app.PublicationCategoryControllerPromiseClient.prototype.destroy =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/dsg_example.example_bib_app.PublicationCategoryController/Destroy',
      request,
      metadata || {},
      methodDescriptor_PublicationCategoryController_Destroy);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.dsg_example.example_bib_app.PublicationCategoryListRequest,
 *   !proto.dsg_example.example_bib_app.PublicationCategoryListResponse>}
 */
const methodDescriptor_PublicationCategoryController_List = new grpc.web.MethodDescriptor(
  '/dsg_example.example_bib_app.PublicationCategoryController/List',
  grpc.web.MethodType.UNARY,
  proto.dsg_example.example_bib_app.PublicationCategoryListRequest,
  proto.dsg_example.example_bib_app.PublicationCategoryListResponse,
  /**
   * @param {!proto.dsg_example.example_bib_app.PublicationCategoryListRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.dsg_example.example_bib_app.PublicationCategoryListResponse.deserializeBinary
);


/**
 * @param {!proto.dsg_example.example_bib_app.PublicationCategoryListRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.dsg_example.example_bib_app.PublicationCategoryListResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.dsg_example.example_bib_app.PublicationCategoryListResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.dsg_example.example_bib_app.PublicationCategoryControllerClient.prototype.list =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/dsg_example.example_bib_app.PublicationCategoryController/List',
      request,
      metadata || {},
      methodDescriptor_PublicationCategoryController_List,
      callback);
};


/**
 * @param {!proto.dsg_example.example_bib_app.PublicationCategoryListRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.dsg_example.example_bib_app.PublicationCategoryListResponse>}
 *     Promise that resolves to the response
 */
proto.dsg_example.example_bib_app.PublicationCategoryControllerPromiseClient.prototype.list =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/dsg_example.example_bib_app.PublicationCategoryController/List',
      request,
      metadata || {},
      methodDescriptor_PublicationCategoryController_List);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.dsg_example.example_bib_app.PublicationCategoryPartialUpdateRequest,
 *   !proto.dsg_example.example_bib_app.PublicationCategoryResponse>}
 */
const methodDescriptor_PublicationCategoryController_PartialUpdate = new grpc.web.MethodDescriptor(
  '/dsg_example.example_bib_app.PublicationCategoryController/PartialUpdate',
  grpc.web.MethodType.UNARY,
  proto.dsg_example.example_bib_app.PublicationCategoryPartialUpdateRequest,
  proto.dsg_example.example_bib_app.PublicationCategoryResponse,
  /**
   * @param {!proto.dsg_example.example_bib_app.PublicationCategoryPartialUpdateRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.dsg_example.example_bib_app.PublicationCategoryResponse.deserializeBinary
);


/**
 * @param {!proto.dsg_example.example_bib_app.PublicationCategoryPartialUpdateRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.dsg_example.example_bib_app.PublicationCategoryResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.dsg_example.example_bib_app.PublicationCategoryResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.dsg_example.example_bib_app.PublicationCategoryControllerClient.prototype.partialUpdate =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/dsg_example.example_bib_app.PublicationCategoryController/PartialUpdate',
      request,
      metadata || {},
      methodDescriptor_PublicationCategoryController_PartialUpdate,
      callback);
};


/**
 * @param {!proto.dsg_example.example_bib_app.PublicationCategoryPartialUpdateRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.dsg_example.example_bib_app.PublicationCategoryResponse>}
 *     Promise that resolves to the response
 */
proto.dsg_example.example_bib_app.PublicationCategoryControllerPromiseClient.prototype.partialUpdate =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/dsg_example.example_bib_app.PublicationCategoryController/PartialUpdate',
      request,
      metadata || {},
      methodDescriptor_PublicationCategoryController_PartialUpdate);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.dsg_example.example_bib_app.PublicationCategoryRetrieveRequest,
 *   !proto.dsg_example.example_bib_app.PublicationCategoryResponse>}
 */
const methodDescriptor_PublicationCategoryController_Retrieve = new grpc.web.MethodDescriptor(
  '/dsg_example.example_bib_app.PublicationCategoryController/Retrieve',
  grpc.web.MethodType.UNARY,
  proto.dsg_example.example_bib_app.PublicationCategoryRetrieveRequest,
  proto.dsg_example.example_bib_app.PublicationCategoryResponse,
  /**
   * @param {!proto.dsg_example.example_bib_app.PublicationCategoryRetrieveRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.dsg_example.example_bib_app.PublicationCategoryResponse.deserializeBinary
);


/**
 * @param {!proto.dsg_example.example_bib_app.PublicationCategoryRetrieveRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.dsg_example.example_bib_app.PublicationCategoryResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.dsg_example.example_bib_app.PublicationCategoryResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.dsg_example.example_bib_app.PublicationCategoryControllerClient.prototype.retrieve =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/dsg_example.example_bib_app.PublicationCategoryController/Retrieve',
      request,
      metadata || {},
      methodDescriptor_PublicationCategoryController_Retrieve,
      callback);
};


/**
 * @param {!proto.dsg_example.example_bib_app.PublicationCategoryRetrieveRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.dsg_example.example_bib_app.PublicationCategoryResponse>}
 *     Promise that resolves to the response
 */
proto.dsg_example.example_bib_app.PublicationCategoryControllerPromiseClient.prototype.retrieve =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/dsg_example.example_bib_app.PublicationCategoryController/Retrieve',
      request,
      metadata || {},
      methodDescriptor_PublicationCategoryController_Retrieve);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.dsg_example.example_bib_app.PublicationCategoryRequest,
 *   !proto.dsg_example.example_bib_app.PublicationCategoryResponse>}
 */
const methodDescriptor_PublicationCategoryController_Update = new grpc.web.MethodDescriptor(
  '/dsg_example.example_bib_app.PublicationCategoryController/Update',
  grpc.web.MethodType.UNARY,
  proto.dsg_example.example_bib_app.PublicationCategoryRequest,
  proto.dsg_example.example_bib_app.PublicationCategoryResponse,
  /**
   * @param {!proto.dsg_example.example_bib_app.PublicationCategoryRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.dsg_example.example_bib_app.PublicationCategoryResponse.deserializeBinary
);


/**
 * @param {!proto.dsg_example.example_bib_app.PublicationCategoryRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.dsg_example.example_bib_app.PublicationCategoryResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.dsg_example.example_bib_app.PublicationCategoryResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.dsg_example.example_bib_app.PublicationCategoryControllerClient.prototype.update =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/dsg_example.example_bib_app.PublicationCategoryController/Update',
      request,
      metadata || {},
      methodDescriptor_PublicationCategoryController_Update,
      callback);
};


/**
 * @param {!proto.dsg_example.example_bib_app.PublicationCategoryRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.dsg_example.example_bib_app.PublicationCategoryResponse>}
 *     Promise that resolves to the response
 */
proto.dsg_example.example_bib_app.PublicationCategoryControllerPromiseClient.prototype.update =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/dsg_example.example_bib_app.PublicationCategoryController/Update',
      request,
      metadata || {},
      methodDescriptor_PublicationCategoryController_Update);
};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.dsg_example.example_bib_app.PublisherControllerClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.dsg_example.example_bib_app.PublisherControllerPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.dsg_example.example_bib_app.PublisherRequest,
 *   !proto.dsg_example.example_bib_app.PublisherResponse>}
 */
const methodDescriptor_PublisherController_Create = new grpc.web.MethodDescriptor(
  '/dsg_example.example_bib_app.PublisherController/Create',
  grpc.web.MethodType.UNARY,
  proto.dsg_example.example_bib_app.PublisherRequest,
  proto.dsg_example.example_bib_app.PublisherResponse,
  /**
   * @param {!proto.dsg_example.example_bib_app.PublisherRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.dsg_example.example_bib_app.PublisherResponse.deserializeBinary
);


/**
 * @param {!proto.dsg_example.example_bib_app.PublisherRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.dsg_example.example_bib_app.PublisherResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.dsg_example.example_bib_app.PublisherResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.dsg_example.example_bib_app.PublisherControllerClient.prototype.create =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/dsg_example.example_bib_app.PublisherController/Create',
      request,
      metadata || {},
      methodDescriptor_PublisherController_Create,
      callback);
};


/**
 * @param {!proto.dsg_example.example_bib_app.PublisherRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.dsg_example.example_bib_app.PublisherResponse>}
 *     Promise that resolves to the response
 */
proto.dsg_example.example_bib_app.PublisherControllerPromiseClient.prototype.create =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/dsg_example.example_bib_app.PublisherController/Create',
      request,
      metadata || {},
      methodDescriptor_PublisherController_Create);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.dsg_example.example_bib_app.PublisherDestroyRequest,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_PublisherController_Destroy = new grpc.web.MethodDescriptor(
  '/dsg_example.example_bib_app.PublisherController/Destroy',
  grpc.web.MethodType.UNARY,
  proto.dsg_example.example_bib_app.PublisherDestroyRequest,
  google_protobuf_empty_pb.Empty,
  /**
   * @param {!proto.dsg_example.example_bib_app.PublisherDestroyRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_protobuf_empty_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.dsg_example.example_bib_app.PublisherDestroyRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.dsg_example.example_bib_app.PublisherControllerClient.prototype.destroy =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/dsg_example.example_bib_app.PublisherController/Destroy',
      request,
      metadata || {},
      methodDescriptor_PublisherController_Destroy,
      callback);
};


/**
 * @param {!proto.dsg_example.example_bib_app.PublisherDestroyRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.dsg_example.example_bib_app.PublisherControllerPromiseClient.prototype.destroy =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/dsg_example.example_bib_app.PublisherController/Destroy',
      request,
      metadata || {},
      methodDescriptor_PublisherController_Destroy);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.dsg_example.example_bib_app.PublisherListRequest,
 *   !proto.dsg_example.example_bib_app.PublisherListResponse>}
 */
const methodDescriptor_PublisherController_List = new grpc.web.MethodDescriptor(
  '/dsg_example.example_bib_app.PublisherController/List',
  grpc.web.MethodType.UNARY,
  proto.dsg_example.example_bib_app.PublisherListRequest,
  proto.dsg_example.example_bib_app.PublisherListResponse,
  /**
   * @param {!proto.dsg_example.example_bib_app.PublisherListRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.dsg_example.example_bib_app.PublisherListResponse.deserializeBinary
);


/**
 * @param {!proto.dsg_example.example_bib_app.PublisherListRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.dsg_example.example_bib_app.PublisherListResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.dsg_example.example_bib_app.PublisherListResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.dsg_example.example_bib_app.PublisherControllerClient.prototype.list =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/dsg_example.example_bib_app.PublisherController/List',
      request,
      metadata || {},
      methodDescriptor_PublisherController_List,
      callback);
};


/**
 * @param {!proto.dsg_example.example_bib_app.PublisherListRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.dsg_example.example_bib_app.PublisherListResponse>}
 *     Promise that resolves to the response
 */
proto.dsg_example.example_bib_app.PublisherControllerPromiseClient.prototype.list =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/dsg_example.example_bib_app.PublisherController/List',
      request,
      metadata || {},
      methodDescriptor_PublisherController_List);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.dsg_example.example_bib_app.PublisherPartialUpdateRequest,
 *   !proto.dsg_example.example_bib_app.PublisherResponse>}
 */
const methodDescriptor_PublisherController_PartialUpdate = new grpc.web.MethodDescriptor(
  '/dsg_example.example_bib_app.PublisherController/PartialUpdate',
  grpc.web.MethodType.UNARY,
  proto.dsg_example.example_bib_app.PublisherPartialUpdateRequest,
  proto.dsg_example.example_bib_app.PublisherResponse,
  /**
   * @param {!proto.dsg_example.example_bib_app.PublisherPartialUpdateRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.dsg_example.example_bib_app.PublisherResponse.deserializeBinary
);


/**
 * @param {!proto.dsg_example.example_bib_app.PublisherPartialUpdateRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.dsg_example.example_bib_app.PublisherResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.dsg_example.example_bib_app.PublisherResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.dsg_example.example_bib_app.PublisherControllerClient.prototype.partialUpdate =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/dsg_example.example_bib_app.PublisherController/PartialUpdate',
      request,
      metadata || {},
      methodDescriptor_PublisherController_PartialUpdate,
      callback);
};


/**
 * @param {!proto.dsg_example.example_bib_app.PublisherPartialUpdateRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.dsg_example.example_bib_app.PublisherResponse>}
 *     Promise that resolves to the response
 */
proto.dsg_example.example_bib_app.PublisherControllerPromiseClient.prototype.partialUpdate =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/dsg_example.example_bib_app.PublisherController/PartialUpdate',
      request,
      metadata || {},
      methodDescriptor_PublisherController_PartialUpdate);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.dsg_example.example_bib_app.PublisherRetrieveRequest,
 *   !proto.dsg_example.example_bib_app.PublisherResponse>}
 */
const methodDescriptor_PublisherController_Retrieve = new grpc.web.MethodDescriptor(
  '/dsg_example.example_bib_app.PublisherController/Retrieve',
  grpc.web.MethodType.UNARY,
  proto.dsg_example.example_bib_app.PublisherRetrieveRequest,
  proto.dsg_example.example_bib_app.PublisherResponse,
  /**
   * @param {!proto.dsg_example.example_bib_app.PublisherRetrieveRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.dsg_example.example_bib_app.PublisherResponse.deserializeBinary
);


/**
 * @param {!proto.dsg_example.example_bib_app.PublisherRetrieveRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.dsg_example.example_bib_app.PublisherResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.dsg_example.example_bib_app.PublisherResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.dsg_example.example_bib_app.PublisherControllerClient.prototype.retrieve =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/dsg_example.example_bib_app.PublisherController/Retrieve',
      request,
      metadata || {},
      methodDescriptor_PublisherController_Retrieve,
      callback);
};


/**
 * @param {!proto.dsg_example.example_bib_app.PublisherRetrieveRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.dsg_example.example_bib_app.PublisherResponse>}
 *     Promise that resolves to the response
 */
proto.dsg_example.example_bib_app.PublisherControllerPromiseClient.prototype.retrieve =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/dsg_example.example_bib_app.PublisherController/Retrieve',
      request,
      metadata || {},
      methodDescriptor_PublisherController_Retrieve);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.dsg_example.example_bib_app.PublisherRequest,
 *   !proto.dsg_example.example_bib_app.PublisherResponse>}
 */
const methodDescriptor_PublisherController_Update = new grpc.web.MethodDescriptor(
  '/dsg_example.example_bib_app.PublisherController/Update',
  grpc.web.MethodType.UNARY,
  proto.dsg_example.example_bib_app.PublisherRequest,
  proto.dsg_example.example_bib_app.PublisherResponse,
  /**
   * @param {!proto.dsg_example.example_bib_app.PublisherRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.dsg_example.example_bib_app.PublisherResponse.deserializeBinary
);


/**
 * @param {!proto.dsg_example.example_bib_app.PublisherRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.dsg_example.example_bib_app.PublisherResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.dsg_example.example_bib_app.PublisherResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.dsg_example.example_bib_app.PublisherControllerClient.prototype.update =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/dsg_example.example_bib_app.PublisherController/Update',
      request,
      metadata || {},
      methodDescriptor_PublisherController_Update,
      callback);
};


/**
 * @param {!proto.dsg_example.example_bib_app.PublisherRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.dsg_example.example_bib_app.PublisherResponse>}
 *     Promise that resolves to the response
 */
proto.dsg_example.example_bib_app.PublisherControllerPromiseClient.prototype.update =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/dsg_example.example_bib_app.PublisherController/Update',
      request,
      metadata || {},
      methodDescriptor_PublisherController_Update);
};


module.exports = proto.dsg_example.example_bib_app;

