[project]
name = "socio_bib_example_grpc"
description = "gRPC interface to socio_bib_example_grpc"
version = "0.2.95"
authors = [{ name = "mark doerr", email = "mark.doerr@uni-greifswald.de" }]
requires-python = "==3.13.*"
dependencies = ["grpcio>=1.73.0"]

[dependency-groups]
dev = ["grpcio-tools>=1.73.0", "pytest>=8,<9", "pytest-cov>=6,<7", "pytest-asyncio"]

[build-system]
requires = ["uv_build>=0.7.13,<0.8.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = "python"

[project.urls]
Documentation = "https://socotecio.gitlab.io/socio-bib-example/"
Source = "https://github.com/socotecio/django-socio-grpc-example/"
