// @generated by protoc-gen-connect-es v0.13.0
// @generated from file proto/socio_bib_example_grpc/v1/example_bib_app.proto (package dsg_example.example_bib_app, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AuthorDestroyRequest, AuthorListRequest, AuthorListResponse, AuthorPartialUpdateRequest, AuthorRequest, AuthorResponse, AuthorRetrieveRequest, BookDestroyRequest, BookListRequest, BookListResponse, BookPartialUpdateRequest, BookRequest, BookResponse, BookRetrieveRequest, BookStreamBooksByIDListRequest, BookStreamBooksByIDListResponse, BookStreamRequest, JournalDestroyRequest, JournalListRequest, JournalListResponse, JournalPartialUpdateRequest, JournalRequest, JournalResponse, JournalRetrieveRequest, PublicationCategoryDestroyRequest, PublicationCategoryListRequest, PublicationCategoryListResponse, PublicationCategoryPartialUpdateRequest, PublicationCategoryRequest, PublicationCategoryResponse, PublicationCategoryRetrieveRequest, PublisherDestroyRequest, PublisherListRequest, PublisherListResponse, PublisherPartialUpdateRequest, PublisherRequest, PublisherResponse, PublisherRetrieveRequest } from "./example_bib_app_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service dsg_example.example_bib_app.AuthorController
 */
export declare const AuthorController: {
  readonly typeName: "dsg_example.example_bib_app.AuthorController",
  readonly methods: {
    /**
     * @generated from rpc dsg_example.example_bib_app.AuthorController.Create
     */
    readonly create: {
      readonly name: "Create",
      readonly I: typeof AuthorRequest,
      readonly O: typeof AuthorResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc dsg_example.example_bib_app.AuthorController.Destroy
     */
    readonly destroy: {
      readonly name: "Destroy",
      readonly I: typeof AuthorDestroyRequest,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc dsg_example.example_bib_app.AuthorController.List
     */
    readonly list: {
      readonly name: "List",
      readonly I: typeof AuthorListRequest,
      readonly O: typeof AuthorListResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc dsg_example.example_bib_app.AuthorController.PartialUpdate
     */
    readonly partialUpdate: {
      readonly name: "PartialUpdate",
      readonly I: typeof AuthorPartialUpdateRequest,
      readonly O: typeof AuthorResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc dsg_example.example_bib_app.AuthorController.Retrieve
     */
    readonly retrieve: {
      readonly name: "Retrieve",
      readonly I: typeof AuthorRetrieveRequest,
      readonly O: typeof AuthorResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc dsg_example.example_bib_app.AuthorController.Update
     */
    readonly update: {
      readonly name: "Update",
      readonly I: typeof AuthorRequest,
      readonly O: typeof AuthorResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

/**
 * @generated from service dsg_example.example_bib_app.BookController
 */
export declare const BookController: {
  readonly typeName: "dsg_example.example_bib_app.BookController",
  readonly methods: {
    /**
     * @generated from rpc dsg_example.example_bib_app.BookController.Create
     */
    readonly create: {
      readonly name: "Create",
      readonly I: typeof BookRequest,
      readonly O: typeof BookResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc dsg_example.example_bib_app.BookController.Destroy
     */
    readonly destroy: {
      readonly name: "Destroy",
      readonly I: typeof BookDestroyRequest,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc dsg_example.example_bib_app.BookController.List
     */
    readonly list: {
      readonly name: "List",
      readonly I: typeof BookListRequest,
      readonly O: typeof BookListResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc dsg_example.example_bib_app.BookController.PartialUpdate
     */
    readonly partialUpdate: {
      readonly name: "PartialUpdate",
      readonly I: typeof BookPartialUpdateRequest,
      readonly O: typeof BookResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc dsg_example.example_bib_app.BookController.Retrieve
     */
    readonly retrieve: {
      readonly name: "Retrieve",
      readonly I: typeof BookRetrieveRequest,
      readonly O: typeof BookResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc dsg_example.example_bib_app.BookController.Stream
     */
    readonly stream: {
      readonly name: "Stream",
      readonly I: typeof BookStreamRequest,
      readonly O: typeof BookResponse,
      readonly kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc dsg_example.example_bib_app.BookController.StreamBooksByIDList
     */
    readonly streamBooksByIDList: {
      readonly name: "StreamBooksByIDList",
      readonly I: typeof BookStreamBooksByIDListRequest,
      readonly O: typeof BookStreamBooksByIDListResponse,
      readonly kind: MethodKind.BiDiStreaming,
    },
    /**
     * @generated from rpc dsg_example.example_bib_app.BookController.Update
     */
    readonly update: {
      readonly name: "Update",
      readonly I: typeof BookRequest,
      readonly O: typeof BookResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

/**
 * @generated from service dsg_example.example_bib_app.JournalController
 */
export declare const JournalController: {
  readonly typeName: "dsg_example.example_bib_app.JournalController",
  readonly methods: {
    /**
     * @generated from rpc dsg_example.example_bib_app.JournalController.Create
     */
    readonly create: {
      readonly name: "Create",
      readonly I: typeof JournalRequest,
      readonly O: typeof JournalResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc dsg_example.example_bib_app.JournalController.Destroy
     */
    readonly destroy: {
      readonly name: "Destroy",
      readonly I: typeof JournalDestroyRequest,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc dsg_example.example_bib_app.JournalController.List
     */
    readonly list: {
      readonly name: "List",
      readonly I: typeof JournalListRequest,
      readonly O: typeof JournalListResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc dsg_example.example_bib_app.JournalController.PartialUpdate
     */
    readonly partialUpdate: {
      readonly name: "PartialUpdate",
      readonly I: typeof JournalPartialUpdateRequest,
      readonly O: typeof JournalResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc dsg_example.example_bib_app.JournalController.Retrieve
     */
    readonly retrieve: {
      readonly name: "Retrieve",
      readonly I: typeof JournalRetrieveRequest,
      readonly O: typeof JournalResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc dsg_example.example_bib_app.JournalController.Update
     */
    readonly update: {
      readonly name: "Update",
      readonly I: typeof JournalRequest,
      readonly O: typeof JournalResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

/**
 * @generated from service dsg_example.example_bib_app.PublicationCategoryController
 */
export declare const PublicationCategoryController: {
  readonly typeName: "dsg_example.example_bib_app.PublicationCategoryController",
  readonly methods: {
    /**
     * @generated from rpc dsg_example.example_bib_app.PublicationCategoryController.Create
     */
    readonly create: {
      readonly name: "Create",
      readonly I: typeof PublicationCategoryRequest,
      readonly O: typeof PublicationCategoryResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc dsg_example.example_bib_app.PublicationCategoryController.Destroy
     */
    readonly destroy: {
      readonly name: "Destroy",
      readonly I: typeof PublicationCategoryDestroyRequest,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc dsg_example.example_bib_app.PublicationCategoryController.List
     */
    readonly list: {
      readonly name: "List",
      readonly I: typeof PublicationCategoryListRequest,
      readonly O: typeof PublicationCategoryListResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc dsg_example.example_bib_app.PublicationCategoryController.PartialUpdate
     */
    readonly partialUpdate: {
      readonly name: "PartialUpdate",
      readonly I: typeof PublicationCategoryPartialUpdateRequest,
      readonly O: typeof PublicationCategoryResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc dsg_example.example_bib_app.PublicationCategoryController.Retrieve
     */
    readonly retrieve: {
      readonly name: "Retrieve",
      readonly I: typeof PublicationCategoryRetrieveRequest,
      readonly O: typeof PublicationCategoryResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc dsg_example.example_bib_app.PublicationCategoryController.Update
     */
    readonly update: {
      readonly name: "Update",
      readonly I: typeof PublicationCategoryRequest,
      readonly O: typeof PublicationCategoryResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

/**
 * @generated from service dsg_example.example_bib_app.PublisherController
 */
export declare const PublisherController: {
  readonly typeName: "dsg_example.example_bib_app.PublisherController",
  readonly methods: {
    /**
     * @generated from rpc dsg_example.example_bib_app.PublisherController.Create
     */
    readonly create: {
      readonly name: "Create",
      readonly I: typeof PublisherRequest,
      readonly O: typeof PublisherResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc dsg_example.example_bib_app.PublisherController.Destroy
     */
    readonly destroy: {
      readonly name: "Destroy",
      readonly I: typeof PublisherDestroyRequest,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc dsg_example.example_bib_app.PublisherController.List
     */
    readonly list: {
      readonly name: "List",
      readonly I: typeof PublisherListRequest,
      readonly O: typeof PublisherListResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc dsg_example.example_bib_app.PublisherController.PartialUpdate
     */
    readonly partialUpdate: {
      readonly name: "PartialUpdate",
      readonly I: typeof PublisherPartialUpdateRequest,
      readonly O: typeof PublisherResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc dsg_example.example_bib_app.PublisherController.Retrieve
     */
    readonly retrieve: {
      readonly name: "Retrieve",
      readonly I: typeof PublisherRetrieveRequest,
      readonly O: typeof PublisherResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc dsg_example.example_bib_app.PublisherController.Update
     */
    readonly update: {
      readonly name: "Update",
      readonly I: typeof PublisherRequest,
      readonly O: typeof PublisherResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

